run:
  timeout: 10m

linters:
  enable:
    - gofmt
    - govet
    - deadcode
    - depguard
    - goimports
    - ineffassign
    - misspell
    - unused
    - varcheck
    - revive
    - staticcheck
    - typecheck
    #- structcheck # FIXME: structcheck is disabled because of generics: https://github.com/golangci/golangci-lint/issues/2649
  disable-all: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # The io/ioutil package has been deprecated.
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
